apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-android
spec:
  selector:
    matchLabels:
      app: api-android
  replicas: 1
  template:
    metadata:
      labels:
        app: api-android
    spec:
      containers:
        - name: api-android
          image: pinolabs/api-android:latest
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
      imagePullSecrets:
        - name: docker
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: api-android
spec:
  selector:
    app: api-android
  ports:
    - name: http
      port: 80
      targetPort: 5000
      nodePort: 30000
  type: NodePort
